{% set version = '0.0.3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dimensionsr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/dimensionsR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dimensionsR/dimensionsR_{{ version }}.tar.gz
  sha256: 8e28a6b0c76cd9bc26851e158b582540971b01c8a86cb606ace45f85ad2f2cae

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-httr
    - r-jsonlite
  run:
    - r-base
    - r-httr
    - r-jsonlite

test:
  commands:
    - $R -e "library('dimensionsR')"           # [not win]
    - "\"%R%\" -e \"library('dimensionsR')\""  # [win]

about:
  home: https://github.com/massimoaria/dimensionsR
  license: GPL-3.0-only
  summary: A set of tools to extract bibliographic content from 'Digital Science Dimensions'
    using 'DSL' API <https://www.dimensions.ai/dimensions-apis/>.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: dimensionsR
# Title: Gathering Bibliographic Records from 'Digital Science Dimensions' Using 'DSL' API
# Version: 0.0.3
# Authors@R: person(given = "Massimo", family = "Aria", role = c("aut", "cre"), email = "massimo.aria@gmail.com", comment = c(ORCID = "0000-0002-8517-9411"))
# Description: A set of tools to extract bibliographic content from 'Digital Science Dimensions' using 'DSL' API <https://www.dimensions.ai/dimensions-apis/>.
# License: GPL-3
# URL: https://github.com/massimoaria/dimensionsR
# BugReports: https://github.com/massimoaria/dimensionsR/issues
# Encoding: UTF-8
# Imports: httr, jsonlite
# Suggests: bibliometrix, knitr, rmarkdown
# RoxygenNote: 7.1.1
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2022-02-07 13:31:09 UTC; massimoaria
# Author: Massimo Aria [aut, cre] (<https://orcid.org/0000-0002-8517-9411>)
# Maintainer: Massimo Aria <massimo.aria@gmail.com>
# Repository: CRAN
# Date/Publication: 2022-02-07 13:50:02 UTC
